# Generated by Django 4.2.13 on 2024-07-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField()),
                ('position', models.IntegerField()),
                ('driver', models.CharField(max_length=100)),
                ('car', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
            ],
        ),
    ]
